#!/usr/bin/env bash

echo "MySQL Root Password: " $MYSQL_ROOT_PASSWORD
echo "MySQL Database Name: " $MYSQL_DATABASE
echo "MySQL Database User: " $MYSQL_USER
echo "MySQL Database Password: " $MYSQL_PASSWORD

QUERY="CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "$QUERY"

QUERY="CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "$QUERY"

QUERY="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, REFERENCES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'%';"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "$QUERY"

# CREATE TEST DATABASES AND USERS
QUERY="CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}_test;"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "$QUERY"

QUERY="CREATE USER IF NOT EXISTS '${MYSQL_USER}_test'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}_test';"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "$QUERY"

QUERY="GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, REFERENCES ON ${MYSQL_DATABASE}_test.* TO '${MYSQL_USER}_test'@'%';"
mysql -uroot -p$MYSQL_ROOT_PASSWORD -e "$QUERY"